# Drycc Community
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  etcd1:
    image: registry.drycc.cc/drycc-addons/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd_data1:/drycc/etcd
  etcd2:
    image: registry.drycc.cc/drycc-addons/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd_data2:/drycc/etcd
  etcd3:
    image: registry.drycc.cc/drycc-addons/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd_data3:/drycc/etcd
  kvrocks-node-1:
    image: registry.drycc.cc/drycc-addons/kvrocks:2.8
    environment:
      - KVROCKS_MASTERAUTH=drycc
      - KVROCKS_REQUIREPASS=drycc
    volumes:
      - kvrocks_node1:/drycc/kvrocks
  kvrocks-node-2:
    image: registry.drycc.cc/drycc-addons/kvrocks:2.8
    environment:
      - KVROCKS_MASTERAUTH=drycc
      - KVROCKS_REQUIREPASS=drycc
    volumes:
      - kvrocks_node2:/drycc/kvrocks
  kvrocks-node-3:
    image: registry.drycc.cc/drycc-addons/kvrocks:2.8
    environment:
      - KVROCKS_MASTERAUTH=drycc
      - KVROCKS_REQUIREPASS=drycc
    volumes:
      - kvrocks_node3:/drycc/kvrocks
  kvrocks-node-4:
    image: registry.drycc.cc/drycc-addons/kvrocks:2.8
    environment:
      - KVROCKS_MASTERAUTH=drycc
      - KVROCKS_REQUIREPASS=drycc
    volumes:
      - kvrocks_node4:/drycc/kvrocks
  kvrocks-controller:
    image: registry.drycc.cc/drycc-addons/kvrocks:2.8
    environment:
      - KVROCKS_MASTERAUTH=drycc
      - KVROCKS_REQUIREPASS=drycc
      - KVROCKS_COMPONENT=controller
      - KVROCKS_CONTROLLER_ETCD_ADDRS=etcd1:2379
    depends_on:
      - kvrocks-node-1
      - kvrocks-node-2
      - kvrocks-node-3
      - kvrocks-node-4
    healthcheck:
      test: ["CMD-SHELL", "curl -sS 127.0.0.1:9379 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
  kvrocks-cluster-init:
    image: registry.drycc.cc/drycc-addons/kvrocks:2.8
    command:
      - /opt/drycc/scripts/kvrocks/cluster-init.sh
    environment:
      - KVROCKS_NODES=kvrocks-node-1:6101,kvrocks-node-2:6101,kvrocks-node-3:6101,kvrocks-node-4:6101
      - KVROCKS_CONTROLLER=http://kvrocks-controller:9379
      - KVROCKS_REPLICA=2
      - KVROCKS_MASTERAUTH=drycc
      - KVROCKS_REQUIREPASS=drycc
    depends_on:
      kvrocks-controller:
        condition: service_healthy

  redis-cluster-proxy:
    image: registry.drycc.cc/drycc-addons/kvrocks:2.8
    depends_on:
      - kvrocks-cluster-init
    ports:
     - 6379:6379
    entrypoint: ['init-stack', '/bin/bash', '-c']
    command:
      - |
        cat << EOF >> "/opt/drycc/kvrocks/etc/redis-proxy.toml"
        [log]
        level = "libproxy=error"                                     # "trace" "info" "debug" "warn" "error"
        ansi = true                                                  # support ANSI colors
        stdout = true                                                # print logs to stdout
        directory = "/tmp"                                           # log file directory
        file_name = "redis-cluster-proxy.log"                        # log file name
        [metrics]
        port = 2110
        [[clusters]]
        name = "redis-cluster-proxy"
        listen_addr = "0.0.0.0:6379"
        hash_tag = "{}"
        thread = 1
        cache_type = "redis_cluster"
        servers = ["kvrocks-node-1:6101", "kvrocks-node-2:6101", "kvrocks-node-3:6101", "kvrocks-node-4:6101"]
        fetch_interval = 1800000                                     # 1800s, 30 minutes
        fetch_since_latest_cmd = 1000                                # 3600s, 1 hour
        read_from_slave = false
        ping_fail_limit = 10
        ping_interval = 300
        read_timeout = 1000
        write_timeout = 1000
        dial_timeout = 500
        listen_proto = "tcp"
        node_connections = 1
        auth = "drycc"
        EOF
        sleep 30s
        redis-cluster-proxy /opt/drycc/kvrocks/etc/redis-proxy.toml
    environment:
      - 'REDIS_PASSWORD=drycc'

volumes:
  etcd_data1:
    driver: local
  etcd_data2:
    driver: local
  etcd_data3:
    driver: local
  kvrocks_node1:
    driver: local
  kvrocks_node2:
    driver: local
  kvrocks_node3:
    driver: local
  kvrocks_node4:
    driver: local
