# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  airflow-worker:
    image: docker.io/drycc/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow_worker_data:/drycc
    command: ["tail", "-f", "/dev/null"]
volumes:
  airflow_worker_data:
    driver: local
