# Copyright Drycc Community.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  postgresql:
    image: registry.drycc.cc/drycc-addons/postgresql:15
    volumes:
      - 'postgresql_data:/drycc/postgresql'
    environment:
      - POSTGRESQL_DATABASE=drycc_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=drycc1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: registry.drycc.cc/drycc-addons/redis:7.0
    volumes:
      - 'redis_data:/drycc'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: registry.drycc.cc/drycc-addons/airflow:3
    environment:
      - AIRFLOW_COMPONENT_TYPE=scheduler
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_APISERVER_HOST=airflow
  airflow-triggerer:
    image: registry.drycc.cc/drycc-addons/airflow:3
    environment:
      - AIRFLOW_COMPONENT_TYPE=triggerer
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_APISERVER_HOST=airflow
  airflow-dag-processor:
    image: registry.drycc.cc/drycc-addons/airflow:3
    environment:
      - AIRFLOW_COMPONENT_TYPE=dag-processor
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_APISERVER_HOST=airflow
  airflow-worker:
    image: registry.drycc.cc/drycc-addons/airflow:3
    environment:
      - AIRFLOW_COMPONENT_TYPE=worker
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_APISERVER_HOST=airflow
  airflow:
    image: registry.drycc.cc/drycc-addons/airflow:3
    environment:
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
