services:
  vminsert:
    image: registry.drycc.cc/drycc-addons/victoriametrics:1
    command:
    - vminsert
    - --httpListenAddr=:8480
    - --storageNode=vmstorage:8400

  vmselect:
    image: registry.drycc.cc/drycc-addons/victoriametrics:1
    command:
    - vmselect
    - --httpListenAddr=:8481
    - --cacheDataPath=/opt/drycc/victoriametrics/data
    - --storageNode=vmstorage:8401

  vmstorage:
    image: registry.drycc.cc/drycc-addons/victoriametrics:1
    command:
    - vmstorage
    - --httpListenAddr=:8482
    - --storageDataPath=/opt/drycc/victoriametrics/data
    - --vminsertAddr=:8400
    - --vmselectAddr=:8401
    - --retentionPeriod=30d
