version: '2'
services:
  redis-node-0:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    ports:
    - 16379:6379
    volumes:
      - redis-cluster_data-0:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-0'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-1'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-2'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-3:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-3'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-4:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-4'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-5:/drycc/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-5'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDISCLI_AUTH=drycc'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

  redis-cluster-proxy:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    depends_on:
      - redis-node-5
    entrypoint: ['init-stack', '/bin/bash', '-c']
    command:
      - |
        cat << EOF >> "/opt/drycc/redis/etc/redis-proxy.toml"
        [log]
        level = "libproxy=error"                                     # "trace" "info" "debug" "warn" "error"
        ansi = true                                                  # support ANSI colors
        stdout = true                                                # print logs to stdout
        directory = "/tmp"                                           # log file directory
        file_name = "redis-cluster-proxy.log"                        # log file name
        [metrics]
        port = 2110
        [[clusters]]
        name = "redis-cluster-proxy"
        listen_addr = "0.0.0.0:6379"
        hash_tag = "{}"
        thread = 1
        cache_type = "redis_cluster"
        servers = ["redis-node-0:6379", "redis-node-1:6379", "redis-node-2:6379", "redis-node-3:6379", "redis-node-4:6379", "redis-node-5:6379"]
        fetch_interval = 1800000                                     # 1800s, 30 minutes
        fetch_since_latest_cmd = 1000                                # 3600s, 1 hour
        read_from_slave = false
        ping_fail_limit = 10
        ping_interval = 300
        read_timeout = 1000
        write_timeout = 1000
        dial_timeout = 500
        listen_proto = "tcp"
        node_connections = 1
        auth = "drycc"
        EOF
        redis-cluster-proxy /opt/drycc/redis/etc/redis-proxy.toml
    environment:
      - 'REDIS_PASSWORD=drycc'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
