version: '2'

services:
  redis-sentinel:
    image: registry.drycc.cc/drycc-addons/redis-sentinel:7.0
    volumes:
      - redis-sentinel_data:/drycc
  redis:
    image: registry.drycc.cc/drycc-addons/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/drycc
volumes:
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local
