# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  postgresql:
    image: docker.io/drycc/postgresql:16
    volumes:
      - 'postgresql_data:/drycc/postgresql'
    environment:
      - POSTGRESQL_DATABASE=drycc_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=drycc1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/drycc/redis:7.0
    volumes:
      - 'redis_data:/drycc'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/drycc/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow_scheduler_data:/drycc
  airflow-worker:
    image: docker.io/drycc/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow_worker_data:/drycc
  airflow:
    image: docker.io/drycc/airflow:2
    environment:
      - AIRFLOW_LDAP_ENABLE=yes
      - AIRFLOW_LDAP_URI=ldap://openldap:1389
      - AIRFLOW_LDAP_SEARCH=dc=example,dc=org
      - AIRFLOW_LDAP_BIND_USER=cn=admin,dc=example,dc=org
      - AIRFLOW_LDAP_BIND_PASSWORD=adminpassword
      - AIRFLOW_LDAP_UID_FIELD=uid
      - AIRFLOW_LDAP_USE_TLS=False
      - AIRFLOW_LDAP_ROLES_MAPPING="{ 'cn=All,ou=Groups,dc=example,dc=org':['User'], 'cn=Admins,ou=Groups,dc=example,dc=org':['Admin'], }"
      - AIRFLOW_LDAP_USER_REGISTRATION_ROLE=Public
      - AIRFLOW_USER_REGISTRATION_ROLE=Public
      - AIRFLOW_DATABASE_NAME=drycc_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=drycc1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_PASSWORD=drycc123
      - AIRFLOW_USERNAME=customuser
      - AIRFLOW_EMAIL=user@example.com
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/drycc
  openldap:
    image: 'docker.io/drycc/openldap:latest'
    ports:
      - '1389:1389'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=customuser
      - LDAP_PASSWORDS=custompassword
    volumes:
      - 'openldap_data:/drycc/openldap'

volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  openldap_data:
    driver: local
