version: '2'
services:
  redis-node-0:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-0'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-1'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-2'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-3:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-3'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-4:/drycc/redis/data
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-4'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    volumes:
      - redis-cluster_data-5:/drycc/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-5'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_PASSWORD=drycc'
      - 'REDISCLI_AUTH=drycc'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

  redis-cluster-proxy:
    image: registry.drycc.cc/drycc-addons/redis-cluster:7.0
    depends_on:
      - redis-node-5
    command:
      - redis-cluster-proxy
      - -startup-nodes=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
      - -addr=0.0.0.0:6379
      - -password=drycc

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
