matrix:
  platform:
    - linux/amd64
    - linux/arm64

clone:
  git:
    image: docker.io/woodpeckerci/plugin-git:2.1.1
    settings:
      partial: false
      depth: 2

labels:
  type: exec
  platform: ${platform}

steps:
- name: publish-linux
  image: bash
  commands:
  - echo $CONTAINER_PASSWORD | podman login $DRYCC_REGISTRY --username $CONTAINER_USERNAME --password-stdin > /dev/null 2>&1
  - bash _scripts/build.sh build
  environment:
    CODENAME:
      from_secret: codename
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    CONTAINER_USERNAME:
      from_secret: container_username
    CONTAINER_PASSWORD:
      from_secret: container_password
  when:
    event:
    - push
