# Copyright Drycc Community
# SPDX-License-Identifier: APACHE-2.0

version: '2.1'

services:
  mysql:
    image: registry.drycc.cc/drycc-addons/mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/drycc/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', '/opt/drycc/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mysql_data:
    driver: local
